Portfolio 1
runVprog/Hello-Microverse pull request #2
Opened 2023-04-27 08:34 UTC by runVprog

Incorporated the linters for HTML and CSS
 - To adhere to the coding standard
Added index.html file
- To provide structure to the webpage
Added Readme template and edited to fit my code
 - To communicate important information about my project
Created CSS file and incorporated it
- to improve the appearance of the html
Added the .gitignore file
- to ignore node modules folder and test.md file

2023-04-27 09:11 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @runVprog , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
- Good commit messages :heavy_check_mark: 
- Good use of the `.gitignore` file :heavy_check_mark: 
- All relevant files created :heavy_check_mark: 
- Linters well setup and passing :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Professional Pull Request summary :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- [ ] I will suggest that you give your Pull Request title a more descriptive name that gives a little information about what the PR is about. I noticed in your Pull Request, You gave it the title `Portfolio 1` however this pull request is based on your `Hello MIcroverse Project` and not your Portfolio. So your pull request title could have been `Hello Microverse Project` or something similar :100: 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 09:11 UTC, nahnahdev commented on README.md
> +
- [ ]  Great job so far @runVprog You've done some impressive work on this project. There are just a few changes you need to make and you'll be on your way to the next project :wink: 
- [ ] I noticed that even though your README contains most of the right details, you have altered the original `Table of contents` of the original Readme template from the [Microverse README Template](https://github.com/microverseinc/readme-template) so currently it contains some of the `Table of Contents` and not all :+1: 
- [ ]  I also noticed that you removed some of the headers from the [Microverse README Template](https://github.com/microverseinc/readme-template). This makes your project incomplete as every section of the readme template is required except for the `FAQ section` which is optional. So please make sure to add all the missing headers/sections in the README template to your project and fill in all the necessary contents :+1:
- [ ] Some of them include the `Getting Started section` the `Acknowledgment`, `Future Features`, and the `Live Demo` For that part under the header you can just put `N/A` or `Coming Soon` since your project hasn't been deployed yet :+1: 
- [ ]  Please ensure that The README also contains the original complete list of `Table of Contents` and ensure that when a topic is clicked on in the table of contents, it takes you to its related section :wink:

2023-04-27 09:11 UTC, nahnahdev commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Your MIT license link currently leads to an error page. I have attached a screenshot below. I think this might be because you don't have a license file in your project. So I will suggest that you include an MIT license file in your project. You can use this [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)  to learn how to add one to your project :wink:
![image](https://user-images.githubusercontent.com/102699958/234812314-755920a6-c9ba-4df3-8c64-9c6193c030b7.png)

- [ ] The MIT License is a popular open-source license that allows others to use, modify, and distribute your code as long as they give credit to you the original author, and include the original license text in their project :100:

2023-04-27 09:11 UTC, nahnahdev commented on README.md
> +
- [ OPTIONAL ] I will suggest you remove this text from your README as it was just a note telling to that Microverse recommends using the MIT License :+1:

2023-04-27 13:47 UTC, AdnanOlarmmi requested changes
Hi @runVprog, 

This is Adnan Is-haq, your beloved code reviewer 🤗,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice setup.
- Nice work ignoring appropriate files.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 13:47 UTC, AdnanOlarmmi commented on README.md
- [ ] Just has the previous reviewer has stated, Kindly complete your readme section, you can follow the readme in [this repo](https://github.com/AdnanOlarmmi/Technopreneur) for inspiration.

2023-04-27 15:57 UTC, runVprog commented on README.md
Thanks Adnan

2023-05-01 08:49 UTC, skyv26 reviewed
## Hi @runVprog , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project with old PR which was unapproved last week. Kindly create a new PR with a good PR description and with the correct `GitHub` flow. Please you just have to create a new branch with a new PR with all requirements. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-01 15:02 UTC, merged